In [1]:
import pandas as pd
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')
import string
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import numpy as np
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Ashish_Parulekar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ashish_Parulekar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ashish_Parulekar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [4]:
Data=pd.read_csv('spam_ham_dataset_Combine.csv',encoding='ISO-8859-1')

In [5]:
Data.head(5)

Unnamed: 0 label                                               text  \
0       605.0   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1      2349.0   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2      3624.0   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3      4685.0  spam  Subject: photoshop , windows , office . cheap ...   
4      2030.0   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0        0.0  
1        0.0  
2        0.0  
3        1.0  
4        0.0

In [6]:
Data.rename(columns={'label':'Target','text':'Messeges'},inplace=True)

In [7]:
Data=Data[['Target','Messeges']]

In [8]:
Data['Target'].replace({'ham':'not spam'},inplace=True)

In [9]:
Data.head(5)

Target                                           Messeges
0  not spam  Subject: enron methanol ; meter # : 988291\r\n...
1  not spam  Subject: hpl nom for january 9 , 2001\r\n( see...
2  not spam  Subject: neon retreat\r\nho ho ho , we ' re ar...
3      spam  Subject: photoshop , windows , office . cheap ...
4  not spam  Subject: re : indian springs\r\nthis deal is t...

In [10]:
Data.tail(5)

Target                                           Messeges
10740      spam  This is the 2nd time we have tried 2 contact u...
10741  not spam              Will Ì_ b going to esplanade fr home?
10742  not spam  Pity, * was in mood for that. So...any other s...
10743  not spam  The guy did some bitching but I acted like i'd...
10744  not spam                         Rofl. Its true to its name

# To check duplicate

In [11]:
duplicate=Data.duplicated().sum()
print('Data is haveing :-' ,duplicate,'duplicate values')

Data is haveing :- 581 duplicate values


In [12]:
Data.shape

(10745, 2)

# Remove Duplicate Rows

In [13]:
Data.drop_duplicates(inplace=True,keep='first')
duplicate=Data.duplicated().sum()
print('Data is haveing :-' ,duplicate,'duplicate values')

Data is haveing :- 0 duplicate values


In [14]:
Data.shape

(10164, 2)

# MissingValue in Data

In [15]:
Data.isnull().sum()

Target      1
Messeges    1
dtype: int64

In [18]:
Data.dropna(inplace=True)

In [19]:
Data.isnull().sum()

Target      0
Messeges    0
dtype: int64

# Encoding_Target_column

In [20]:
"0='not_spam'"
"1='spam'"

Data['Target'].replace({'spam':1,'not spam':0},inplace=True)

In [21]:
Data.head(10)

Target                                           Messeges
0       0  Subject: enron methanol ; meter # : 988291\r\n...
1       0  Subject: hpl nom for january 9 , 2001\r\n( see...
2       0  Subject: neon retreat\r\nho ho ho , we ' re ar...
3       1  Subject: photoshop , windows , office . cheap ...
4       0  Subject: re : indian springs\r\nthis deal is t...
5       0  Subject: ehronline web address change\r\nthis ...
6       0  Subject: spring savings certificate - take 30 ...
7       1  Subject: looking for medication ? we ` re the ...
8       0  Subject: noms / actual flow for 2 / 26\r\nwe a...
9       0  Subject: nominations for oct . 21 - 23 , 2000\...

In [22]:
stop_words=set(stopwords.words('english'))
poctuation=string.punctuation

In [23]:
def Text_processing(text):
    process_text=[]
    tk=nltk.word_tokenize(text)
    stop_words=set(stopwords.words('english'))
    for i in tk:
        i=i.lower()
        if ((i not in stop_words) & (i not in string.punctuation)):
            la=WordNetLemmatizer()
            i=la.lemmatize(i)
            process_text.append(i)
    return  process_text
            
            
    
    

In [24]:
Data['Processed_Text']=Data['Messeges'].apply(Text_processing)

In [25]:
Data['Processed_Text']=Data['Processed_Text'].apply(lambda x:' '.join(x))

In [26]:
Data.head(5)

Target                                           Messeges  \
0       0  Subject: enron methanol ; meter # : 988291\r\n...   
1       0  Subject: hpl nom for january 9 , 2001\r\n( see...   
2       0  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3       1  Subject: photoshop , windows , office . cheap ...   
4       0  Subject: re : indian springs\r\nthis deal is t...   

                                      Processed_Text  
0  subject enron methanol meter 988291 follow not...  
1  subject hpl nom january 9 2001 see attached fi...  
2  subject neon retreat ho ho ho around wonderful...  
3  subject photoshop window office cheap main tre...  
4  subject indian spring deal book teco pvr reven...

In [27]:
Data.shape

(10163, 3)

# Conver Text in Vector

# Count_Vectoriztion

In [28]:
Cv=CountVectorizer(stop_words='english',)

In [29]:
Cv_text=Cv.fit_transform(Data['Processed_Text']).toarray()

In [30]:
Cv.vocabulary_

{'subject': 44263,
 'enron': 19223,
 'methanol': 31644,
 'meter': 31638,
 '988291': 5315,
 'follow': 21317,
 'note': 33891,
 'gave': 22243,
 'monday': 32338,
 '00': 0,
 'preliminary': 37390,
 'flow': 21207,
 'data': 15846,
 'provided': 37910,
 'daren': 15786,
 'override': 35187,
 'pop': 37011,
 'daily': 15687,
 'volume': 48673,
 'presently': 37454,
 'zero': 51070,
 'reflect': 39339,
 'activity': 5842,
 'obtain': 34244,
 'gas': 22190,
 'control': 14509,
 'change': 12549,
 'needed': 33273,
 'asap': 7909,
 'economics': 18420,
 'purpose': 38152,
 'hpl': 24987,
 'nom': 33767,
 'january': 27170,
 '2001': 1463,
 'attached': 8193,
 'file': 20865,
 'hplnol': 24994,
 '09': 383,
 'xl': 50377,
 'neon': 33338,
 'retreat': 39958,
 'ho': 24645,
 'wonderful': 49841,
 'time': 45927,
 'year': 50656,
 'leader': 29192,
 'know': 28497,
 'extremely': 20231,
 'hectic': 24154,
 'tough': 46322,
 'think': 45703,
 'past': 35638,
 'holiday': 24698,
 'life': 29526,
 'week': 49227,
 'december': 16076,
 '25': 1770,


In [32]:
Cv_text

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Spliting Data in x & y


In [34]:
x_Cv=Cv_text

In [35]:
y_Cv=Data['Target']

In [36]:
x_train_Cv,x_test_Cv,y_train_Cv,y_test_Cv=train_test_split(x_Cv,y_Cv,train_size=0.7,random_state=50)

# TF-IDF Vectoriztion

In [37]:
TF=TfidfVectorizer(stop_words='english')

In [38]:
TF_text=TF.fit_transform(Data['Processed_Text']).toarray()

In [39]:
TF_text

array([[0.11566511, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Spliting Data in  x & y

In [40]:
x_TF=TF_text

In [41]:
y_TF=Data['Target']

In [42]:
x_train_TF,x_test_TF,y_train_TF,y_test_TF=train_test_split(x_TF,y_TF,train_size=0.7,random_state=50)

# Model_Selection Based Count_Vectrizer

In [43]:
from sklearn.linear_model import LogisticRegression
Log=LogisticRegression()

In [44]:
Log.fit(x_train_Cv,y_train_Cv)

LogisticRegression()

In [45]:
print('Train_Score_Log:',round(Log.score(x_train_Cv,y_train_Cv),3))
print('Test_Score_Log:',round(Log.score(x_test_Cv,y_test_Cv),3))

Train_Score_Log: 0.997
Test_Score_Log: 0.967


In [46]:
Log_test_pri=Log.predict(x_test_Cv)

In [47]:
from sklearn.metrics import confusion_matrix,classification_report

In [48]:
print(confusion_matrix(y_test_Cv,Log_test_pri))

[[2374   26]
 [  74  575]]


In [49]:
print(classification_report(y_test_Cv,Log_test_pri))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      2400
           1       0.96      0.89      0.92       649

    accuracy                           0.97      3049
   macro avg       0.96      0.94      0.95      3049
weighted avg       0.97      0.97      0.97      3049



In [50]:
"0='not_spam'"
"1='spam'"

"1='spam'"

In [61]:
def Spam_Detection(text):
    text=Text_processing(text)
    text=" ".join(text)
    Vector=Cv.transform([text]).toarray()
    result=Log.predict(Vector)
    if(result==0):
        return '** Not_Spam **'
    else:
        return '** Spam **'
        

In [62]:
Log_test_pri='Congratulations! You’re being offered a no-interest Visa credit card. Click here to claim: https://bit.ly/07tjA786'



In [63]:
Log_test_pri="Hi This is to confirm that we have received your email and our Learner Success Manager will get back to you with an appropriate resolution.We appreciate you reaching us and we will get back to you at the earliest. In the meantime, you can visit Simplilearn Community Forum and engage with our customers & experts for your learning needs.Your ticket number for this interaction is 01397664."

In [64]:
T=Spam_Detection(Log_test_pri)
T

'** Not_Spam **'

# Saving two Model

# 1)Cv   2)Log

In [65]:
import pickle

In [66]:
pickle.dump([Cv,Log],open('Spam_Mail_Detection','wb'))

In [68]:
import os as os

In [127]:
os.getcwd()

'C:\\Users\\Ashish_Parulekar\\PYTHON_FILES\\Spam_text_detection'

In [111]:
text=" ".join(T)

In [112]:
text

'’ issue payment information recent order yq-885629 take action http //bit.ly/hp187ty19'

In [114]:
 Vector=Cv.transform([text]).toarray()

In [115]:
 Vector.ndim

2

In [119]:
result=Log.predict(Vector)

In [120]:
check=Spam_Detection(Log_test_pri)

In [121]:
check

'Spam'