In [1]:
import pandas as pd
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')
import string
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import numpy as np
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Ashish_Parulekar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ashish_Parulekar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ashish_Parulekar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
Data=pd.read_csv('spam_ham_dataset_Combine.csv',encoding='ISO-8859-1')

In [3]:
Data.head(5)

Unnamed: 0 label                                               text  \
0       605.0   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1      2349.0   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2      3624.0   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3      4685.0  spam  Subject: photoshop , windows , office . cheap ...   
4      2030.0   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0        0.0  
1        0.0  
2        0.0  
3        1.0  
4        0.0

In [4]:
Data.rename(columns={'label':'Target','text':'Messeges'},inplace=True)

In [5]:
Data=Data[['Target','Messeges']]

In [6]:
Data['Target'].replace({'ham':'not spam'},inplace=True)

In [7]:
Data.head(5)

Target                                           Messeges
0  not spam  Subject: enron methanol ; meter # : 988291\r\n...
1  not spam  Subject: hpl nom for january 9 , 2001\r\n( see...
2  not spam  Subject: neon retreat\r\nho ho ho , we ' re ar...
3      spam  Subject: photoshop , windows , office . cheap ...
4  not spam  Subject: re : indian springs\r\nthis deal is t...

In [8]:
Data.tail(5)

Target                                           Messeges
10745   spam   Best Exciting Offers On Home & kitchen | Get ...
10746   spam                    Spin the Wheel, get a SURPRISE!
10747   spam                  Cookware & Dining | Up To 70% OFF
10748   spam  Are you looking to diversify your portfolio to...
10749   spam           Don’t Miss India’s Biggest Fashion Sale!

# To check duplicate

In [9]:
duplicate=Data.duplicated().sum()
print('Data is haveing :-' ,duplicate,'duplicate values')

Data is haveing :- 581 duplicate values


In [10]:
Data.shape

(10750, 2)

# Remove Duplicate Rows

In [11]:
Data.drop_duplicates(inplace=True,keep='first')
duplicate=Data.duplicated().sum()
print('Data is haveing :-' ,duplicate,'duplicate values')

Data is haveing :- 0 duplicate values


In [12]:
Data.shape

(10169, 2)

# MissingValue in Data

In [13]:
Data.isnull().sum()

Target      1
Messeges    1
dtype: int64

In [14]:
Data.dropna(inplace=True)

In [15]:
Data.isnull().sum()

Target      0
Messeges    0
dtype: int64

# Encoding_Target_column

In [16]:
"0='not_spam'"
"1='spam'"

Data['Target'].replace({'spam':1,'not spam':0},inplace=True)

In [17]:
Data.head(10)

Target                                           Messeges
0       0  Subject: enron methanol ; meter # : 988291\r\n...
1       0  Subject: hpl nom for january 9 , 2001\r\n( see...
2       0  Subject: neon retreat\r\nho ho ho , we ' re ar...
3       1  Subject: photoshop , windows , office . cheap ...
4       0  Subject: re : indian springs\r\nthis deal is t...
5       0  Subject: ehronline web address change\r\nthis ...
6       0  Subject: spring savings certificate - take 30 ...
7       1  Subject: looking for medication ? we ` re the ...
8       0  Subject: noms / actual flow for 2 / 26\r\nwe a...
9       0  Subject: nominations for oct . 21 - 23 , 2000\...

In [18]:
stop_words=set(stopwords.words('english'))
poctuation=string.punctuation

In [19]:
def Text_processing(text):
    process_text=[]
    tk=nltk.word_tokenize(text)
    stop_words=set(stopwords.words('english'))
    for i in tk:
        i=i.lower()
        if ((i not in stop_words) & (i not in string.punctuation)):
            la=WordNetLemmatizer()
            i=la.lemmatize(i)
            process_text.append(i)
    return  process_text
            
            
    
    

In [20]:
Data['Processed_Text']=Data['Messeges'].apply(Text_processing)

In [21]:
Data['Processed_Text']=Data['Processed_Text'].apply(lambda x:' '.join(x))

In [22]:
Data.head(5)

Target                                           Messeges  \
0       0  Subject: enron methanol ; meter # : 988291\r\n...   
1       0  Subject: hpl nom for january 9 , 2001\r\n( see...   
2       0  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3       1  Subject: photoshop , windows , office . cheap ...   
4       0  Subject: re : indian springs\r\nthis deal is t...   

                                      Processed_Text  
0  subject enron methanol meter 988291 follow not...  
1  subject hpl nom january 9 2001 see attached fi...  
2  subject neon retreat ho ho ho around wonderful...  
3  subject photoshop window office cheap main tre...  
4  subject indian spring deal book teco pvr reven...

In [23]:
Data.shape

(10168, 3)

# Conver Text in Vector

# Count_Vectoriztion

In [24]:
Cv=CountVectorizer(stop_words='english',)

In [25]:
Cv_text=Cv.fit_transform(Data['Processed_Text']).toarray()

In [26]:
Cv.vocabulary_

{'subject': 44265,
 'enron': 19225,
 'methanol': 31646,
 'meter': 31640,
 '988291': 5315,
 'follow': 21319,
 'note': 33893,
 'gave': 22245,
 'monday': 32340,
 '00': 0,
 'preliminary': 37392,
 'flow': 21209,
 'data': 15848,
 'provided': 37912,
 'daren': 15788,
 'override': 35189,
 'pop': 37013,
 'daily': 15689,
 'volume': 48675,
 'presently': 37456,
 'zero': 51072,
 'reflect': 39341,
 'activity': 5842,
 'obtain': 34246,
 'gas': 22192,
 'control': 14510,
 'change': 12550,
 'needed': 33275,
 'asap': 7909,
 'economics': 18422,
 'purpose': 38154,
 'hpl': 24989,
 'nom': 33769,
 'january': 27172,
 '2001': 1463,
 'attached': 8194,
 'file': 20867,
 'hplnol': 24996,
 '09': 383,
 'xl': 50379,
 'neon': 33340,
 'retreat': 39960,
 'ho': 24647,
 'wonderful': 49843,
 'time': 45929,
 'year': 50658,
 'leader': 29194,
 'know': 28499,
 'extremely': 20233,
 'hectic': 24156,
 'tough': 46324,
 'think': 45705,
 'past': 35640,
 'holiday': 24700,
 'life': 29528,
 'week': 49229,
 'december': 16078,
 '25': 1770,


In [34]:
Cv_text

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Spliting Data in x & y


In [35]:
x_Cv=Cv_text

In [36]:
y_Cv=Data['Target']

In [37]:
x_train_Cv,x_test_Cv,y_train_Cv,y_test_Cv=train_test_split(x_Cv,y_Cv,train_size=0.7,random_state=50)

# TF-IDF Vectoriztion

In [38]:
TF=TfidfVectorizer(stop_words='english')

In [39]:
TF_text=TF.fit_transform(Data['Processed_Text']).toarray()

In [40]:
TF_text

array([[0.11567072, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Spliting Data in  x & y

In [41]:
x_TF=TF_text

In [42]:
y_TF=Data['Target']

In [43]:
x_train_TF,x_test_TF,y_train_TF,y_test_TF=train_test_split(x_TF,y_TF,train_size=0.7,random_state=50)

# Model_Selection Based Count_Vectrizer

In [44]:
from sklearn.linear_model import LogisticRegression
Log=LogisticRegression()

In [45]:
Log.fit(x_train_Cv,y_train_Cv)

LogisticRegression()

In [46]:
print('Train_Score_Log:',round(Log.score(x_train_Cv,y_train_Cv),3))
print('Test_Score_Log:',round(Log.score(x_test_Cv,y_test_Cv),3))

Train_Score_Log: 0.997
Test_Score_Log: 0.968


In [47]:
Log_test_pri=Log.predict(x_test_Cv)

In [48]:
from sklearn.metrics import confusion_matrix,classification_report

In [49]:
print(confusion_matrix(y_test_Cv,Log_test_pri))

[[2402   32]
 [  66  551]]


In [50]:
print(classification_report(y_test_Cv,Log_test_pri))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      2434
           1       0.95      0.89      0.92       617

    accuracy                           0.97      3051
   macro avg       0.96      0.94      0.95      3051
weighted avg       0.97      0.97      0.97      3051



In [51]:
"0='not_spam'"
"1='spam'"

"1='spam'"

In [52]:
def Spam_Detection(text):
    text=Text_processing(text)
    text=" ".join(text)
    Vector=Cv.transform([text]).toarray()
    result=Log.predict(Vector)
    if(result==0):
        return '** Not_Spam **'
    else:
        return '** Spam **'
        

In [53]:
#Log_test_pri='Congratulations! You’re being offered a no-interest Visa credit card. Click here to claim: https://bit.ly/07tjA786'



In [56]:
#Log_test_pri="Hi This is to confirm that we have received your email and our Learner Success Manager will get back to you with an appropriate resolution.We appreciate you reaching us and we will get back to you at the earliest. In the meantime, you can visit Simplilearn Community Forum and engage with our customers & experts for your learning needs.Your ticket number for this interaction is 01397664."

In [57]:
Log_test_pri='Are you looking to diversify your portfolio to bring more stability to your investments? Then Axis Triple Advantage Fund might be the one for you!It is a 3-in-1 investment option or an asset allocation fund which helps you diversify your money across the three asset categories of equity, debt, and gold to provide you with risk-adjusted returns.'

In [58]:
#Log_test_pri='Don’t Miss India’s Biggest Fashion Sale!'

In [60]:
T=Spam_Detection(Log_test_pri)
T

'** Not_Spam **'

# Saving two Model

# 1)Cv   2)Log

In [61]:
import pickle

In [62]:
pickle.dump([Cv,Log],open('Spam_Mail_Detection','wb'))

In [68]:
import os as os

In [127]:
os.getcwd()

'C:\\Users\\Ashish_Parulekar\\PYTHON_FILES\\Spam_text_detection'

In [111]:
text=" ".join(T)

In [112]:
text

'’ issue payment information recent order yq-885629 take action http //bit.ly/hp187ty19'

In [114]:
 Vector=Cv.transform([text]).toarray()

In [115]:
 Vector.ndim

2

In [119]:
result=Log.predict(Vector)

In [120]:
check=Spam_Detection(Log_test_pri)

In [121]:
check

'Spam'